extends: substitution
message: "Use'%s' instead of '%s'."
#ignorecase: true
level: suggestion
action:
  name: replace
swap:
  K8s: Kubernetes
  k8s: Kubernetes
  id: ID
  API's: APIs
  config: configuration
  Config: Configuration
  Openshift: OpenShift
  github: GitHub
  Github: GitHub