extends: substitution
message: "Use'%s' instead of '%s'."
#ignorecase: true
level: suggestion
action:
  name: replace
swap:
  Air gapped: Air-gapped
  air gapped: air-gapped
  API's: APIs
  config: configuration
  Config: Configuration
  ElasticSearch: Elasticsearch
  fluentd: Fluentd
  helm: Helm
  id: ID
  K8s: Kubernetes
  k8s: Kubernetes
  Openshift: OpenShift