extends: substitution
message: "Use'%s' instead of '%s'."
#ignorecase: true
level: suggestion
action:
  name: replace
swap:
  API's: APIs
  config: configuration
  Config: Configuration
  Air gapped: Air-gapped
  air gapped: air-gapped
  helm: Helm
  id: ID
  K8s: Kubernetes
  k8s: Kubernetes