extends: Microsoft.Acronyms
message: "'%s' has no definition."
level: suggestion
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - STY
  - STJ
  - STQL
  - STS
  - STML