extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: suggestion
action:
  name: replace
swap:
  '(?:drive C:|drive C>|C: drive)': drive C
  '(?:internet bot|web robot)s?': bot(s)
  '(?:microsoft cloud|the cloud)': cloud
  '(?:mobile|smart) ?phone': phone
  '24/7': every day
  'audio(?:-| )book': audiobook
  'back(?:-| )light': backlight
  'chat ?bots?': chatbot(s)
  adaptor: adapter
  administrate: administer
  afterwards: afterward
  alphabetic: alphabetical
  alphanumerical: alphanumeric
  anti-aliasing: antialiasing
  anti-malware: antimalware
  anti-spyware: antispyware
  anti-virus: antivirus
  appendixes: appendices
  artificial intelligence: artificial intelligence
  assembler: assembly language
  bpp: bpp
  bps: bps
  caap: CaaP
  conversation-as-a-platform: conversation as a platform
  eb: EB
  gb: GB
  gbps: Gbps
  kb: KB
  keypress: keystroke
  mb: MB
  pb: PB
  tb: TB
  zb: ZB
  viz: namely
  ergo: therefore
  K8s: Kubernetes
  k8s: Kubernetes
  id: ID
  API's: APIs
  config: configuration
  Config: Configuration
  timeseries: time series
  time-series: time series
  stackstate[?a-z]: StackState