name: "Draft SaaS docs site"
# generate new version of draft SaaS docs site when changes are merged to branch STAC-14132-saas-docs-v

on:
  push:
    branches: [ STAC-14132-saas-docs-v3 ]

jobs:
  generate_draft_saas:
    name: GenerateDraftSaasSite
    concurrency: draft-saas-docs
    runs-on: windows-latest
    steps:
    - name: setup git config
      run: |
        # setup the username and email
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: checkout
      uses: actions/checkout@v2
    - name: ConvertWithScript
      run: |
        perl resources/convert-docs-to-saas.pl
    - name: commit
      run: |
        # Stage the file, commit and push
        git add -A
        git commit -m "TEST rebuild draft SaaS docs from STAC-14132-saas-docs-v3"
        git push origin stac-saas-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   auto-pull-request:
#     concurrency: draft-saas-docs
#     runs-on: ubuntu-latest
#     steps:
#     - name: pull-request-action
#       uses: vsoch/pull-request-action@1.0.18
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         PULL_REQUEST_BRANCH: draft-saas-docs
#         PULL_REQUEST_TITLE: "[AUTOMATED] new saas docs generated from STAC-14132-saas-docs-v3"
#         PULL_REQUEST_REVIEWERS: "gggina"
