name: "Draft SaaS docs site"
# generate new version of draft SaaS docs site when changes are merged to branch STAC-14132-saas-docs-v

on: push
jobs:
  generate_draft_saas:
    name: GenerateDraftSaasSite
    runs-on: windows-latest
    steps:
    - name: Delete old SaaS branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: draft-saas-docs
    - name: Extract source branch name (current branch)
      shell: bash
      run: echo "##[set-output name=SOURCE_BRANCH_NAME;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: create new SaaS branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'draft-saas-docs'
#     - name: checkout SaaS source branch
#       uses: actions/checkout@v2
    - name: checkout draft-saas-docs branch
      uses: actions/checkout@v2
      with:
        ref: draft-saas-docs
    - name: ConvertWithScript
      run: |
        perl resources/convert-docs-to-saas.pl
    - name: git config, commit
      run: |
        # Stage changes and commit
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add -A
        git commit -m "Rebuild draft SaaS docs from ${{ steps.extract_branch.outputs.SOURCE_BRANCH_NAME }}"
    - name: git push new branch
      run: |        
         git push -u origin draft-saas-docs
