name: "Draft SaaS docs site"
# generate new version of draft SaaS docs site when changes are merged to branch STAC-14132-saas-docs-v

on:
  push:
    branches: [ STAC-14132-saas-docs-v3 ]

jobs:
  generate_draft_saas:
    name: GenerateDraftSaasSite
    runs-on: windows-latest
    steps:
    - name: Delete old SaaS branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: stac-saas-docs-test
    - name: checkout SaaS source branch
      uses: actions/checkout@v2
      with:
        ref: STAC-14132-saas-docs-v3
    - name: ConvertWithScript
      run: |
        perl resources/convert-docs-to-saas.pl
    - name: git config, commit
      run: |
        # Stage the file, commit and push
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status
        git add -A
        git commit -m "TEST rebuild draft SaaS docs from STAC-14132-saas-docs-v3"
    - name: create new SaaS branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'NEW-stac-saas-docs-test'
#     - name: git push new branch
#       run: |        
#         git push -u origin stac-saas-docs-test
