name: Merge 4.5 changes into master

# triggered on push or merge to 4.5 branch
on:
  push:
    branches: [ 4.5 ]

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: "[AUTOMATED] Sync updates from live branch 4.5"
          PULL_REQUEST_REVIEWERS: "gggina"
