name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# triggered on merge to 4.4 branch
on:
  push:
    branches: [ 4.4 ]

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: "[AUTOMATED] Sync updates from live branch 4.4"
          PULL_REQUEST_REVIEWERS: "gggina"
