name: Merge 5.1 changes into master

# triggered on push or merge to 5.1 branch
on:
  push:
    branches: [ 5.1 ]

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: "[AUTOMATED] Sync updates from live branch 5.1"
          PULL_REQUEST_REVIEWERS: "gggina"
