name: Merge 5.0 changes into master

# triggered on push or merge to 50 branch
on:
  push:
    branches: [ 5.0 ]

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: "[AUTOMATED] Sync updates from live branch 5.0"
          PULL_REQUEST_REVIEWERS: "gggina"
