name: vale-markdown-linter
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: errata-ai/vale-action@v2.0.1
      with:
        debug: true
        reporter: github-pr-review
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
