name: vale-markdown-linter
on: [pull_request]

jobs:
  vale-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        json: true
    - name: List changed files
#      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
        echo "These files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
#    - name: vale
#      uses: errata-ai/vale-action@reviewdog
#      with:
##        files: ${{ steps.files.outputs.all }}
#        debug: true
#        reporter: github-pr-review
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
