name: vale-markdown-linter
on: [pull_request]

jobs:
  vale-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: vale
      uses: errata-ai/vale-action@reviewdog
      with:
        debug: true
        reporter: github-pr-review
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
