# Checks committed text based on the Microsoft styleguide and StackState vocab list
# only files changed in the PR will be checked
# comments on changes are added as a review on the PR by the github-actionsbot

name: brokenlink-checker
on: [push]

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run brokenlink checker
      run: python .github/scripts/brokenlinks.py
      shell: sh
