name: vale-markdown-linter
on: [pull_request]

jobs:
  vale-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - name: vale
      uses: errata-ai/vale-action@reviewdog
      with:
#        files: ${{ steps.files.outputs.all }}
        debug: true
        reporter: github-pr-review
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
